### PR TITLE
build: adding explicit node version for local dev

### PR DESCRIPTION
**Pull request by iloveitaly**
this could be tied into CI builds as well

### CODE REVIEW

**Review by Mr0grog — CHANGES_REQUESTED** [review]
I appreciate the intent here, but I don’t think I’m going to incorporate this for a couple reasons:

1. As a package meant to support Node.js 16.x and later, there’s not really a “correct” version here. The `download-fixtures` script requires Node.js 18.x, but only to avoid an extra dev dependency. Everything else (tests, builds, etc.) is intended to support all current versions of Node.js, and my intent has been that a packaged published on NPM will do so as well.

    Ultimately, requiring specific runtime versions is appropriate for an application where you control the deployment environment, but that is not the case here.

2. This is specific to asdf. If we’re going to add this, we should probably be adding similar files for other environment/tooling managers, like Nodenv, NVM, etc.

On the other hand, if you wanted to change this to specify a range of versions in [the `engines` field of `package.json`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json?v=true#engines), that’d be great. I’m also fine if you want to add a `.gitignore` line for this file so you can use it locally. 👍

**Comment by iloveitaly** [comment]
1. My thought is it's harder for new devs on the project to jump in: (a) they need to figure out what a good nodejs version is for development and (b) this makes a version explicit that should be used for non-matrix builds on CI (i.e. linting, package publishing, etc)
2. Yup, makes sense! Would you be open to configuring this using a nvm file since that is more popular?

**Comment by Mr0grog** [comment]
> My thought is it's harder for new devs on the project to jump in… this makes a version explicit that should be used for non-matrix builds on CI (i.e. linting, package publishing, etc)

Just to be clear, Node 18 should *only* be required for the `download-fixtures` script, not for any other dev tasks. That specific script is the special case, not dev tasks. (That said, I get it; Node 18 will work for *all* the things, sort of [see below], and Node 16 will not.)

> Would you be open to configuring this using a nvm file since that is more popular?

No. Here’s a slightly different framing of my original points that might be clearer:

1. This tool needs to work in Node.js 16, and it therefore needs to be easy to test in Node.js 16 locally. I don’t want to have to delete or change git-managed files (like `.tool-versions` or `.nvmrc` or `.node-version` or whatever) or do something complex in order to locally reproduce a Node 16-only failure from CI. (Perhaps I should have just made `node-fetch` a dev dependency instead of making this one script special. <----- Also a change you could make that would solve this issue?)

2. If I wasn’t worried about (1), we would still need to add `.tool-versions` *and* `.node-version` *and* `.nvmrc`, and then make sure they all stay up-to-date and in sync, which in my experience is error-prone (and I’d _like_ to avoid adding even more complexity by templating all those files or something).

I appreciate where you’re coming from here, and I am also a *strong* proponent of keeping these files in the repo for projects where the deployment environment is under the dev team’s control. That is not this nature of this project, though.

**Comment by Mr0grog** [comment]
And again, if you wanted to change this to add a `.gitignore` entry for this file so you can use it locally, and/or specify a range of versions in [the `engines` field of `package.json`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json?v=true#engines), that’d be great! Or even switch to using `undici` or `node-fetch` or something. 👍

**Comment by Mr0grog** [comment]
@iloveitaly I’m going to close this, but I want to say thanks again for bringing this up. 🙏 If I didn’t say so before, I definitely think you identified some legitimate issues/barriers for contributors here, even if we couldn’t agree on a correct solution. Instead, I’ve done some of the things I suggested here in #100: specify valid Node.js versions in `package.json`, ensure all the scripts and tooling work in those versions, and ignore config files for asdf, nodenv, etc. so people can use them locally without having conflicts.

Hopefully that addresses most of your actual goals here.

**Comment by iloveitaly** [comment]
Awesome! That sound like a good solution.

**Pull request closed without merging**
