### PR TITLE
Support code formatting

### LINKED ISSUE #63: Supporting conversion of inline code formatting to backticked text
Google Docs recently added pseudo backtick-style inline-code formatting. e.g. if you enter "This is \`inline\` code" it will look like this:

Screenshot 2023-05-12 at 11 52 05 AM

### PR DESCRIPTION
**Pull request by Mr0grog**
Google Docs doesn’t have a native way to represent code, but if you turn on "Automatically detect Markdown" in Google Docs, it will format text between backticks as monospaced and green. Based on that, it seems like monospaced text is probably worth considering as "code" and formatting it as such in markdown.

This adds support both for inline code (with backticks in markdown) and for code blocks (indented in markdown — that's the default for hast-util-to-mdast, rather than fenced blocks, even though I like fences more).

Still to do:
- [x] Inline code with backticks
- [x] Understanding lines that are all code as code blocks
- [x] Understanding consecutive lines as one block

Fixes #63.

### CODE REVIEW

**Comment by Mr0grog** [comment]
Also occurs to me that two consecutive runs of *inline* code (but with different formatting, e.g. colors) will probably show up wrong here. Need to test.

**Comment by Mr0grog** [comment]
@bensheldon obviously this isn't 100% yet, but if you've got time to try this on any real-world Docs that led to #63, please let me know if you see issues.

**Comment by bensheldon** [comment]
@Mr0grog I think that commit you just now pushed causes it to work for this document 👍🏻 :

https://docs.google.com/document/d/17Q99br9iQVIcuNln7wCN0qSTosk_vd8oGY3nR_EFkp8/edit?usp=sharing

**Comment by Mr0grog** [comment]
Sweet!

I’ve noticed some broken-ness with this around consecutive inline code text with different formatting:

consective-inline-code-spans

And around paragraphs with complete *lines* that are code (probably common in lists):

paragraph-with-code-lines
<br>
list-item-with-code-lines

Need to take a break for the evening; will think about whether I should ship this for now (probably works for most common cases?) or wait and fix those more complex situations.

**Comment by Mr0grog** [comment]
Ugh, also it's possible for a list item `<li>` to carry monospaced formatting while a `<span>` inside it carries *non*-monospaced formatting. This *seems* to happen when you hit enter while the cursor is in one list item (to make a new list item) and in text that is monospaced, then type some text, and go back and un-monospace some of the text in the new list item. So it takes some doing, but I’d guess there are lots of oddball ways to get in this situation. So I need a test case to cover that.

It doesn't look like this is possible on paragraphs, so it *might* be unique to `<li>`. I also need to test whether it can occur with other styling, like bold, italic, or strikethrough.

In this situation, the `<span>` elements inside the list item each have monospaced or non-monospaced styles, so the font on the list item itself is redundant. I *think* that means there is a relatively easy solution: disregard font style information on block elements.

**Comment by Mr0grog** [comment]
Update: yep, this is possible with other styles, not just the font. Filing this as a separate issue: #65.

**Comment by Mr0grog** [comment]
OK, this should be more-or-less good to go. I split up my original test into 3: inline code, block-level code, and some edge-case-y block-level stuff that I didn't solve here and set the tests to skip for now.

Solving for an issue with multiple colors or styles in inline code had the nice side-effect of streamlining *all* our inline formatting where different styles overlap, e.g. this:

```markdown
This **is bold** **_and italic_**.
```

Is now:

```markdown
This **is bold _and italic_**.
```

Which is pretty great.

**Pull request merged**
